{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "ebe6c119_e7669f83",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 31042
      },
      "writtenOn": "2023-11-06T21:05:34Z",
      "side": 1,
      "message": "CI failure looks like a flake?",
      "revId": "159d21ece38df32aa1f6d4bce6d73c08e142914b",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "17886661_507c5bb8",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 5020
      },
      "writtenOn": "2023-11-06T21:14:32Z",
      "side": 1,
      "message": "\u003e CI failure looks like a flake?\n\nYes, I reran it. In cases like this if you\u0027d like to retry the job you can try to log in on the libaom__commit_trigger page with a Google based account. You should then see a Retrigger link in the left column unless it\u0027s already been started.",
      "parentUuid": "ebe6c119_e7669f83",
      "revId": "159d21ece38df32aa1f6d4bce6d73c08e142914b",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0"
    }
  ]
}