{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "88748de8_549e5282",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 5020
      },
      "writtenOn": "2021-04-08T05:04:26Z",
      "side": 1,
      "message": "These are progressing well enough, if there\u0027s another warning failure we can just push this directly",
      "revId": "aed8375926eca0be8650bc190903d777bf706c28",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "3de39f86_48d8923d",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 5290
      },
      "writtenOn": "2021-04-08T05:10:32Z",
      "side": 1,
      "message": "Earlier run failed due to the warning fixed by next commit: https://build.aomedia.org/jenkins/job/libaom__example_test/30586/gcc/new/\n\nSo, I\u0027ll force-push this one.",
      "parentUuid": "88748de8_549e5282",
      "revId": "aed8375926eca0be8650bc190903d777bf706c28",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0"
    }
  ]
}